# Generated by Django 2.2.5 on 2019-11-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191114_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='aminities',
            new_name='amenities',
        ),
    ]
